<a href="https://colab.research.google.com/github/ShymaShameer/Eniac_project/blob/main/Project_QC_selcting_data_for_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project**
**Case Study: Eniac’s Discount Strategy**

To guarantee analytical accuracy, quality audit performed to validate completeness and consistency. This involved pruning the dataset of non-essential noise—specifically outliers and incomplete orders—to focus exclusively on the data points that drive strategic insights.

# Importing clean data

In [1]:
import pandas as pd

In [2]:
# orders_cl.csv
url = "https://drive.google.com/file/d/1VnxyeSbF4U3ZvSECrGp7nOfeZWVTGt8c/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
#orders_cl = pd.read_csv(path)
orders_cl=pd.read_csv(path, parse_dates=["created_date"])


# orderlines_cl.csv
url = "https://drive.google.com/file/d/1UKKFde6KcY6kmaA838mdXkJKWltwjk94/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
orderlines_cl=pd.read_csv(path, parse_dates=["orderlines_date"])

# products_cl.csv
url = "https://drive.google.com/file/d/1rSTmYVMWz8T-S7MlXc3EVaakMQ-XABDt/view?usp=sharing"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
products_cl=pd.read_csv(path)

url = 'https://drive.google.com/file/d/1m1ThDDIYRTTii-rqM5SEQjJ8McidJskD/view?usp=drive_link'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
brands_df_original = pd.read_csv(path)

In [3]:
# copy of all dataframes
orders_df = orders_cl.copy()
orderlines_df = orderlines_cl.copy()
products_df=products_cl.copy()
brands_df = brands_df_original.copy()

In [4]:
# Display format
pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_colwidth', None) # to increase the width of the columns

## Orders

In [5]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226904 entries, 0 to 226903
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226904 non-null  int64
 1   created_date  226904 non-null  datetime64[ns]
 2   total_paid    226904 non-null  float64
 3   state         226904 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 6.9+ MB

In [6]:
orders_df.describe().round(2)

       order_id                   created_date  total_paid
count 226904.00                         226904   226904.00
mean  413295.87  2017-09-06 14:58:03.124224512      569.23
min   241319.00            2017-01-01 00:07:19        0.00
25%   356261.75  2017-05-17 08:01:00.750000128       34.19
50%   413037.50     2017-10-16 21:00:01.500000      112.99
75%   470554.25  2017-12-24 15:56:53.249999872      525.98
max   527401.00            2018-03-14 13:58:36   214747.53
std    65919.83                            NaN     1761.78

## Orderlines

In [7]:
orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   order_id          293983 non-null  int64
 2   product_quantity  293983 non-null  int64
 3   sku               293983 non-null  object
 4   orderlines_date   293983 non-null  datetime64[ns]
 5   unit_price        293983 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 13.5+ MB

In [8]:
orderlines_df.describe().round(2)

,id,order_id,product_quantity,orderlines_date,unit_price
count,293983.00,293983.00,293983.00,293983,293983.00
mean,1397918.10,419999.12,1.12,2017-09-19 03:19:26.305779712,409.86
min,1119109.00,241319.00,1.00,2017-01-01 00:07:19,-119.00
25%,1262542.50,362258.50,1.00,2017-06-06 16:20:34.500000,35.99
50%,1406940.00,425956.00,1.00,2017-11-13 21:13:53,92.99
75%,1531321.50,478657.00,1.00,2018-01-02 04:47:03,339.58
max,1650203.00,527401.00,999.00,2018-03-14 13:58:36,159989.83
std,153009.56,66344.49,3.40,NaN,837.07

## Products

In [9]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10534 entries, 0 to 10533
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sku        10534 non-null  object
 1   name       10534 non-null  object
 2   desc       10534 non-null  object
 3   price      10534 non-null  float64
 4   in_stock   10534 non-null  int64
 5   type       10484 non-null  float64
 6   short_sku  10534 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 576.2+ KB

In [10]:
products_df.describe().round(2)

         price  in_stock                type
count 10534.00  10534.00            10484.00
mean    641.16      0.19  146302850159717.69
std    1337.86      0.40  903238784037626.12
min       2.99      0.00             1216.00
25%      42.05      0.00             1433.00
50%     103.22      0.00         11905404.00
75%     599.00      0.00         12645406.00
max   15339.00      1.00 5740000000000000.00

## Brands

In [11]:
brands_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   short   187 non-null    object
 1   long    187 non-null    object
dtypes: object(2)
memory usage: 3.1+ KB

In [12]:
brands_df.describe()

       short   long
count    187    187
unique   187    181
top      8MO  Apple
freq       1      2

# Selecting data required for analysis

## Rectifying incorrect brand names( long)

In [11]:
brands_df.duplicated().sum()

np.int64(0)

In [15]:
# merging product & brand dataframes
product_brand_df= products_df.merge(brands_df, left_on= "short_sku", right_on= "short")
product_brand_df

,sku,name,desc,price,in_stock,type,short_sku,short,long
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696.00,RAI,RAI,Rain Design
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401.00,APP,APP,Apple
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387.00,APP,APP,Apple
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230.00,APP,APP,Apple
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pro (2006/07/08).,34.99,1,1364.00,KIN,KIN,Kingston
...,...,...,...,...,...,...,...,...,...
10318,BEL0376,Belkin Travel Support Apple Watch Black,compact and portable stand vertically or horizontally for Apple Watch,29.99,1,12282.00,BEL,BEL,Belkin
10319,THU0060,"Enroute Thule 14L Backpack MacBook 13 ""Black",Backpack with capacity of 14 liter compartments MacBook up to 13 inches up to 10 inches Cases,69.95,1,1392.00,THU,THU,Thule
10320,THU0061,"Enroute Thule 14L Backpack MacBook 13 ""Blue",Backpack with capacity of 14 liter compartments MacBook up to 13 inches up to 10 inches Cases,69.95,1,1392.00,THU,THU,Thule
10321,THU0062,"Enroute Thule 14L Backpack MacBook 13 ""Red",Backpack with capacity of 14 liter compartments MacBook up to 13 inches up to 10 inches Cases,69.95,0,1392.00,THU,THU,Thule
10322,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartments MacBook up to 13 inches up to 10 inches Cases,69.95,1,1392.00,THU,THU,Thule

In [17]:
# Renaming 'long' and 'short'

product_brand_df = product_brand_df.rename(columns={
    "long": "brand name",
    "short": "brand_name_short"})

In [18]:
# Deleting the 'short_sku' column
product_brand_df = product_brand_df.drop(columns=["short_sku"], errors='ignore')

In [19]:
product_brand_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10323 entries, 0 to 10322
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sku               10323 non-null  object
 1   name              10323 non-null  object
 2   desc              10323 non-null  object
 3   price             10323 non-null  float64
 4   in_stock          10323 non-null  int64
 5   type              10275 non-null  float64
 6   brand_name_short  10323 non-null  object
 7   brand name        10323 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 645.3+ KB

* checking for each brand short names with duplicate long names & replacing with the correct long names (for "KEN" & "MUJ")

In [20]:
brands_df.loc[brands_df["long"].duplicated(keep=False)].sort_values("long")

    short      long
6     AP2     Apple
7     APP     Apple
17    BOS      Bose
19    CAD      Bose
67    JYB   Jaybird
70    KEN   Jaybird
94    MOP    Mophie
98    MUJ    Mophie
117   OTR  Startech
153   STA  Startech
37    ENV   Unknown
80    LIB   Unknown

In [21]:
# AP2
product_brand_df.loc[product_brand_df["brand_name_short"]=="AP2",:].shape[0]

349

In [22]:
# APP
product_brand_df.loc[product_brand_df["brand_name_short"]=="APP",:]#.shape[0]

,sku,name,desc,price,in_stock,type,brand_name_short,brand name
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401.00,APP,Apple
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387.00,APP,Apple
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230.00,APP,Apple
5,APP0073,Apple Composite AV Cable iPhone and iPod white,IPhone and iPod AV Cable Dock to Composite Video.,45.00,0,1230.00,APP,Apple
9,APP0100,Apple Adapter Mini Display Port to VGA,Adapter Mini Display Port to VGA MacBook and MacBook Pro (unibody).,35.00,0,1325.00,APP,Apple
...,...,...,...,...,...,...,...,...
10197,APP2576,Apple 42mm Violeta Correa Deportiva,durable and flexible sports strap with clip closure for Apple Watch 42 mm,59.00,0,2449.00,APP,Apple
10237,APP2477-A,Open - Apple iPhone 8 Plus 64GB Space Gray,Apple iPhone 8 Plus 64GB Space Gray,919.00,0,113281716.00,APP,Apple
10238,APP1973-A,Open - Apple iPad Wi-Fi 128GB Space Gray,Apple iPad Wi-Fi 128GB Space Gray (MP2H2TY / A),502.81,0,113851714.00,APP,Apple
10241,APP1472,Apple Magic Keyboard English International,English keyboard Mac and Apple iPad Ultrathin Bluetooth.,119.00,1,13855401.00,APP,Apple
10269,APP1466,Apple Magic Mouse 2 (OEM),Apple Bluetooth wireless mouse original box,89.00,1,1387.00,APP,Apple

In [ ]:
# BOS
product_brand_df.loc[product_brand_df["brand_name_short"]=="BOS",:]#.shape[0]

In [ ]:
# CAD
product_brand_df.loc[product_brand_df["brand_name_short"]=="CAD",:]#.shape[0]

In [23]:
# JYB
product_brand_df.loc[product_brand_df["brand_name_short"]=="JYB",:]#.shape[0]

,sku,name,desc,price,in_stock,type,brand_name_short,brand name
8447,JYB0007,X3 Jaybird Wireless Bluetooth Headset Black,In-ear headphones waterproof and wireless 8 hours of autonomous iPhone iPad iPod powder and Apple Watch,129.00,0,5384.00,JYB,Jaybird
8448,JYB0008,Jaybird Freedom Bluetooth Headphones Red,In-ear headphones small metallic design Bluetooth connection for iPhone iPad iPod and Apple Watch,149.99,0,5384.00,JYB,Jaybird
8449,JYB0009,Jaybird Freedom Bluetooth Headphones White,In-ear headphones small metallic design Bluetooth connection for iPhone iPad iPod and Apple Watch,149.99,0,5384.00,JYB,Jaybird
8450,JYB0010,Jaybird Freedom Bluetooth Headphones Black,In-ear headphones small metallic design Bluetooth connection for iPhone iPad iPod and Apple Watch,149.99,0,5384.00,JYB,Jaybird

In [24]:
# KEN
product_brand_df.loc[product_brand_df["brand_name_short"]=="KEN",:]#.shape[0]

,sku,name,desc,price,in_stock,type,brand_name_short,brand name
36,KEN0028,Kensington ClickSafe lock Mac and PC,Mac and PC padlock with keys.,54.99,0,1325.00,KEN,Jaybird
77,KEN0045,Kensington Essentials Stand iPad Stand black,Universal support for iPad tablets.,29.99,0,1216.00,KEN,Jaybird
78,KEN0046,Kensington Essentials Stand iPad Stand white,Universal support for iPad tablets.,19.99,0,1216.00,KEN,Jaybird
185,KEN0059,Kensington Soft Case cover iPhone 5 / 5S black,Soft Case iPhone 5 / 5S.,14.99,0,11865403.00,KEN,Jaybird
186,KEN0062,Kensington Thin Back Case iPhone 5 / 5S Gray,Back Case iPhone 5 / 5S.,19.99,0,11865403.00,KEN,Jaybird
187,KEN0063,Kensington Thin Back Case iPhone 5 / 5S Pink,Back Case iPhone 5 / 5S.,19.99,0,11865403.00,KEN,Jaybird
309,KEN0064,"Safestand Kensington security lock iMac 27 """,key lock station for iMac 27 inches.,99.99,0,1325.00,KEN,Jaybird
329,KEN0078,Kensington Easy Riser Notebook PC and Mac,Support for Mac portable and adjustable PC.,24.99,0,8696.00,KEN,Jaybird
330,KEN0079,Kensington Expert Presenter Green Laser Pointer,laser pointer 10X bright green.,76.99,0,1229.00,KEN,Jaybird
332,KEN0080,Kensington Presenter Expert green laser pointer with 4GB,laser pointer green + USB 4GB 10 times brighter,89.99,0,1229.00,KEN,Jaybird
333,KEN0081,Kensington Expert Presenter Red Laser Pointer,Red laser pointer for presentations color.,49.99,0,1229.00,KEN,Jaybird
337,KEN0093,ClickSave Kensington Laptop Cable Lock,Security cable with combination laptop Mac and PC.,49.99,0,1325.00,KEN,Jaybird
338,KEN0094,"Kensington Cable, retractable Mac and PC",retractable cable Mac and PC combination.,29.99,1,1325.00,KEN,Jaybird
361,KEN0096,Kensington Evap Water Rescue Pouch bag wet salvation,Salvation bag for iPhone and iPod exposed to moisture.,19.99,0,11905404.00,KEN,Jaybird
393,KEN0105,Kensington MicroSaver Keyed security lock MacBook UltraBook,cable lock with safety lock for MacBook.,69.99,0,1325.00,KEN,Jaybird
497,KEN0109,"Backpack Trek Triple Kensington MacBook 13 ""Black",Backpack for MacBook Pro / Air 13-inch,60.49,0,1392.00,KEN,Jaybird
498,KEN0110,"Bandolier Trek Triple Kensington MacBook 13 """,Triple Trek bandolier for your MacBook Pro / Air 13 inches.,43.99,0,1392.00,KEN,Jaybird
499,KEN0111,"Triple Kensington Trek briefcase MacBook 13 ""Black",briefcase vertical opening for MacBook / Air 13 inches.,54.99,0,1392.00,KEN,Jaybird
580,KEN0129,Portofolio Kensington Soft Case iPad Mini / Retina Green,Flexible Book cover type for new iPad Mini Retina.,28.99,0,12635403.00,KEN,Jaybird
739,KEN0166,PowerBolt Kensington 3.4 Dual Charger with Lightning Cable Car,Car Charger fast charging with double connection: USB (1A) and Lightning cable (24A) for iPhone and iPad,43.99,0,13615399.00,KEN,Jaybird
789,KEN0172,Kensington GummyGrip Kids Children Pointer iPad Gray,Children pointer with thick tip for iPad iPhone and iPod Touch.,12.99,0,1229.00,KEN,Jaybird
791,KEN0171,Kensington Absolute Power International Power Adapter,International Adapter with 2 USB ports entry USA / Japan Australia / UK and European China.,34.99,0,14365395.00,KEN,Jaybird
808,KEN0174,Kensington SafeGrip iPad Air Rugged Case with Stand NII ± or Carbon,Shockproof housing for children with handle for iPad.,43.99,0,12635403.00,KEN,Jaybird
813,KEN0175,Kensington SafeGrip iPad Air Rugged Case with Stand NII ± or Blue,Shockproof housing with handle for iPad.,43.99,0,12635403.00,KEN,Jaybird
862,KEN0179,Kensington BlackBelt 2nd Degree Case iPad Mini / Retina Lila,Shock resistant housing military rubber for iPad Mini / Retina.,39.99,0,12635403.00,KEN,Jaybird
1251,KEN0194,Kensington 7-port USB 3.0 pockethub,Charger and USB 3.0 HUB with 7 ports.,59.99,0,13005399.00,KEN,Jaybird
1374,KEN0196,Kensington Folio Case Cover Customize Me iPad Air 2 Red,Lockable customizable universal type book for iPad Air 2.,39.99,0,12635403.00,KEN,Jaybird
1410,KEN0206,UA3000E Kensington USB 3.0 to Ethernet Adapter Gigabyte USB 3-Port Hub + 3.0,Adapter USB 3.0 to Ethernet Hub Gigabyte and 3 USB 3.0 ports for Mac and PC.,56.09,0,12585395.00,KEN,Jaybird
1411,KEN0209,UH4000 Kensington 4-Port USB 3.0 Hub,Hub 4 USB 3.0 ports for Mac and PC.,27.49,0,12995397.00,KEN,Jaybird
1428,KEN0208,Kensington UH4000C Hub 4 port power supply,Mac and PC Hub 4 USB 3.0 ports.,44.99,0,12995397.00,KEN,Jaybird
1437,KEN0195,Kensington Folio Case Cover Customize Me iPad Air 2 Black,customizable cover with book closure type for iPad Air 2,39.99,0,12635403.00,KEN,Jaybird
1454,KEN0200,Kensington KeyFolio Plus X2 Thin Case with backlit keyboard iPad Air 2 Black,Cover with Spanish backlit keyboard for iPad Air 2,109.99,0,12575403.00,KEN,Jaybird
1476,KEN0211,Kensington Power Bank 10400 mAh External Battery,10400mAh external battery small and light for iPhone iPad and iPod.,59.99,0,1515.00,KEN,Jaybird
1493,KEN0204,"Bandolier LM340 Kensington 14.4 ""Gray",Padded shoulder strap with compartments and Macbook cases up to 144 inches.,49.99,0,1392.00,KEN,Jaybird
1546,KEN0201,Kensington KeyFolio X3 Thin Keyboard and Case for iPad Air 2 Battery Black,Spanish keyboard holster and battery for iPad Air 2,109.99,0,12635403.00,KEN,Jaybird
1613,KEN0207,Kensington UA0000E Gigabyte Ethernet Adapter USB 3.0,Gigabyte Ethernet adapter to USB 3.0.,29.99,0,12585395.00,KEN,Jaybird
1857,KEN0212,Kensington Power Bank External Battery 5200mAh Silver,5200mAh external battery small and light (152g) for iPhone iPad and iPod.,32.99,0,1515.00,KEN,Jaybird
2089,KEN0210,PresentAir Kensington Presenter Pro Bluetooth 4.0 LE,Bluetooth laser pointer.,59.99,0,12085400.00,KEN,Jaybird
2275,KEN0218,Slot Adapter Kit security Kensington,Safety kit with adapter slot MacBook Air.,16.49,0,12355400.00,KEN,Jaybird
2297,KEN0203-A,(Open) UH4000 Kensington 4-Port USB 3.0 Hub,Hub 4 USB 3.0 ports for Mac and PC.,27.49,0,1298.00,KEN,Jaybird
2390,KEN0220,Kensingnton Minisaver security Cable for Mac and PC,Cable ultralight Mac and PC security.,69.99,0,1325.00,KEN,Jaybird
2392,KEN0223,Kensington BlackBelt 1st Degree Rugged Case for iPad Air 2 Black,Black Case for iPad Air 2.,29.99,0,12635403.00,KEN,Jaybird
2393,KEN0224,Kensington BlackBelt 2nd Degree Rugged Case for iPad Air 2 Black,Shock resistant housing rubber IPAD Air 2.,44.99,0,12635403.00,KEN,Jaybird
2394,KEN0225,Kensington SafeGrip Case for iPad mini resistant Verde,Hard Case for iPad Mini with handle.,39.99,0,12635403.00,KEN,Jaybird
2396,KEN0227,Kensington BlackBelt 1st Degree Rugged Case for iPad Mini Black,Light and protective cover for iPad Mini.,24.99,0,12635403.00,KEN,Jaybird
2398,KEN0226,Kensington BlackBelt 2nd Degree Rugged Case for iPad Mini Black,Shock resistant housing military rubber iPad Mini.,34.99,0,12635403.00,KEN,Jaybird
3011,KEN0230,VM1000 Kensington Mini DisplayPort to VGA 2K,Video Adapter Mini Display to VGA.,29.99,0,12585395.00,KEN,Jaybird
3013,KEN0229,VM2000 Kensington Mini DisplayPort to HDMI Adapter 2K,Video Adapter Mini Display to HDMI.,29.99,0,12585395.00,KEN,Jaybird
3171,KEN0232,VM4000 Kensington Mini Display Port Adapter to HDMI 4K,4K resolution video adapter Mini Display to HDMI.,36.99,0,12585395.00,KEN,Jaybird
3669,KEN0235,Kensington SecureBack Air Rugged Case 1/2 Black,Ultra-resistant sleeve anchor with click and lock iPad Air 1/2,60.99,0,12635403.00,KEN,Jaybird
3692,KEN0234,SecureBack Kensington Case iPad Air / 2 Black,Cover with click and lock anchor for iPad Air 1/2.,59.99,0,12635403.00,KEN,Jaybird
3806,KEN0236,Kensington MP230L black mouse accuracy,Precision Wireless Mouse for Mac and PC.,59.99,0,1387.00,KEN,Jaybird
3876,KEN0237,Kensington MicroSaver Security Cable 18m,Security Cable lock for Mac and PC laptops.,49.49,0,1325.00,KEN,Jaybird
4594,KEN0240,Kensington PowerBolt 5.2A Dual USB Car Charger,26W Car Charger Dual USB for iPhone and iPad,29.99,0,13615399.00,KEN,Jaybird
4595,KEN0241,Kensington PowerBolt fast car charger 2.4A,Car Charger with USB 2.0 port for fast charging for iPad iPhone and iPod,19.99,0,13615399.00,KEN,Jaybird
4596,KEN0242,SD3500v Kensington Docking USB 3.0 / DVI / HDMI / Ethernet,Dock with multiple USB connections 3.0 DVI / HDMI / DVI and Ethernet adapters VGA / HDMI for Mac and PC,194.99,0,12995397.00,KEN,Jaybird
4630,KEN0243,Dock Kensington USB-C to USB 3.1 / USB-C / Ethernet / HDMI,USB-Hub USB 3.1 ports C / USB-C / Ethernet / HDMI (compatible with Thunderbolt 3) for Mac and PC,310.99,0,12585395.00,KEN,Jaybird
4633,KEN0238,Kensington Lift Off MacBook Support,Support and height-adjustable base with ventilation slot MacBook,29.99,0,8696.00,KEN,Jaybird
4645,KEN0239,Kensington Support Macbook with fan,Stand with two fans and USB connection for MacBook,39.99,0,8696.00,KEN,Jaybird
4793,KEN0228,Kensington Docking Station USB 3.0 to VGA / HDMI / DVI,Dock with 6 USB ports and dual video connector for Mac and PC,164.99,0,12995397.00,KEN,Jaybird
4863,KEN0244,Dock Kensington SD4500 USB USB 3.1-C / Ethernet / HDMI,Dock USB-C USB 3.1 Ethernet HDMI (compatible with Thunderbolt 3) for Mac,279.99,0,12585395.00,KEN,Jaybird
5420,KEN0245,Kensington USB Dock SD1500-C to USB 3.0 / HDMI / VGA / Ethernet Notebook,Laptop Dock with 4 ports and 4K video output cable included USB-C for Mac and PC,105.99,0,12585395.00,KEN,Jaybird
6188,KEN0022-A,Open - Kensington ClickSafe lock Mac and PC,Mac and PC padlock with keys.,42.99,0,1298.00,KEN,Jaybird
6524,KEN0237-A,Open - Kensington USB-C USB 3.1 ports Dock / USB-C / Ethernet / HDMI / Thunderbolt 3,Dock USB-C USB 3.1 / USB-C / Ethernet / HDMI / 3-port Thunderbolt Mac and PC,310.99,0,12585395.00,KEN,Jaybird
6628,KEN0247,CV2000V Kensington USB-C to VGA Full HD Black,USB-C adapter with VGA resolution FHD for Mac and PC,36.29,0,12585395.00,KEN,Jaybird
6632,KEN0248,CV4000H Kensington USB adapter to HDMI 4K-C Black,USB-C adapter supports HDMI 4K resolution for Mac and PC,49.99,0,12585395.00,KEN,Jaybird
8105,KEN0249,Kensington Security Locking Station 2.0 Adapter MacBook,Adapter anchoring safety key and compact design for MacBook model 11 inches to 15 inches,120.01,0,12355400.00,KEN,Jaybird
8726,KEN0239-A,Open - Kensington USB Dock SD1500-C to USB 3.0 / HDMI / VGA / Ethernet Notebook,Refurbished Laptop Dock with 4 ports and 4K video output cable included USB-C for Mac and PC,105.99,0,1298.00,KEN,Jaybird

In [25]:
brands_df.loc[brands_df["short"] == "KEN", "long"] = "Kensington"

In [ ]:
# MOP
product_brand_df.loc[product_brand_df["brand_name_short"]=="MOP",:]#.shape[0]

In [ ]:
# MUJ
product_brand_df.loc[product_brand_df["brand_name_short"]=="MUJ",:]#.shape[0]

In [ ]:
brands_df.loc[brands_df["short"] == "MUJ", "long"] = "Mujjo"

In [ ]:
# ENV
product_brand_df.loc[product_brand_df["brand_name_short"]=="ENV",:]#.shape[0]

In [ ]:
# LIB
product_brand_df.loc[product_brand_df["brand_name_short"]=="LIB",:]#.shape[0]

In [26]:
# STA
product_brand_df.loc[product_brand_df["brand_name_short"]=="STA",:]#.shape[0]

,sku,name,desc,price,in_stock,type,brand_name_short,brand name
778,STA0015,Startech Adapter FireWire 800 to FireWire 400,FireWire adapter FW 800 to FW400.,10.99,0,12355400.00,STA,Startech
802,STA0016,Startech Mini DisplayPort to DisplayPort Cable 18m,Adapdator Cable Mini Display Port Male to Display Port.,12.99,0,1325.00,STA,Startech
933,STA0013,Startech USB 2.0 cable type A male B 5m,USB 2.0 cable type A male B 5m.,6.99,1,1325.00,STA,Startech
1610,STA0009,Startech HDMI M / M Black 2m,Cable HDMI M / M black 2 meters.,12.99,1,1325.00,STA,Startech
1619,STA0017,Startech HDMI M / M Ultra HD 4K Black 3m,Cable HDMI M / M 3m Ultra HD 4k black 3D Ready and Ethernet.,14.99,1,1325.00,STA,Startech
1622,STA0018,Startech HDMI M / M Ultra HD 4K Black 5m,Cable HDMI M / M 5m Ultra HD 4K 3D Ready and Ethernet.,19.99,1,1325.00,STA,Startech
1848,STA0020,Startech Ethernet cable 15 meters Gray Unit Class 6,Ethernet cable 15 meters Unit Class 6 Mac and PC.,16.99,1,1325.00,STA,Startech
1855,STA0011,Startech USB Cable black 18m extension,18 meters extension USB cable.,4.79,0,1325.00,STA,Startech
1969,STA0019,Startech Adapter with Micro Mini-Jack 35mm 2 connectors,Adapter headset jack Mini-4-pin mini-jack 2 3 pin.,9.99,0,1325.00,STA,Startech
2113,STA0008,Startech DVI-D dual link M / M 18m,Cable DVI-D 18 double bond meters.,11.99,0,1325.00,STA,Startech
2177,STA0030,Startech Adapter Cable Lightning to Micro USB-B Female Black,Cable Lightning to Micro USB adapter for charging and syncing for iPhone iPad and iPod Touch.,22.99,0,1325.00,STA,Startech
2209,STA0021,Startech HDMI M / M black 1mt,HDMI Cable 1 meter with 2 male ports for Mac.,9.99,1,1325.00,STA,Startech
2318,STA0022,Startech Video Converter Cable Mini DisplayPort to VGA,Cable Mini DisplayPort to VGA.,41.99,1,1325.00,STA,Startech
2325,STA0023,Startech Adapter Kit Mini DisplayPort / VGA / HDMI / USB 3.0 / Gigabit Ethernet,Mini DisplayPort adapter kit / HDMI / VGA / USB 3.0 / Ethernet.,86.99,0,1325.00,STA,Startech
2326,STA0024,Startech Adapter Kit Ethernet / USB 3.0 / VGA / Mini DisplayPort,Two adapter cables Mini DisplayPort to VGA and USB 3.0 to Ethernet.,81.99,0,1325.00,STA,Startech
2327,STA0025,Startech 21A Lightning Car Charger with USB 2.0,Dual car charger Lightning and USB 2.0 for iPhone and iPad.,44.99,0,13615399.00,STA,Startech
2328,STA0026,Startech Adapter Lightning to Micro USB-B Female White,Lightning to Micro USB Adapter for iPhone-B generation iPad and iPod Touch 6A.,16.99,0,14365395.00,STA,Startech
2329,STA0027,Startech Lightning to USB Cable 30cm Black,Lightning 30cm USB cable to charge and sync iPhone iPad and iPod.,19.99,0,1325.00,STA,Startech
2330,STA0028,Startech Adapter Cable Lightning to Micro USB-B Female White,Cable Lightning to Micro USB adapter for charging and syncing for iPhone iPad and iPod Touch.,22.99,0,1325.00,STA,Startech
2331,STA0029,Startech Lightning to USB Cable 3m White,Lightning 3 m Cable for iPhone iPad and iPod Touch.,30.99,0,1325.00,STA,Startech
2332,STA0031,Startech Lightning to USB Cable 1m,Lightning USB cable 1m for charging and syncing iPhone iPad and iPod.,15.99,0,1325.00,STA,Startech
3844,STA0010-A,Open - Startech Cable Mini Display Port to Display Port 18m,Adapdator Cable Mini Display Port Male to Display Port,12.99,0,1298.00,STA,Startech
5904,STA0032,Startech Gigabit Ethernet Cable Cat. 6 2m Gray,Ethernet Cable 2 meters Mac and PC Unit Class 6,4.99,1,1325.00,STA,Startech
5905,STA0033,StarTech Gigabit Ethernet Cable Cat. 6 5m Gray,Ethernet Cable 5 meter Mac and PC Unit Class 6,7.99,1,1325.00,STA,Startech
6202,STA0034,Startech Adapter Black Thunderbolt Thunderbolt 3,Thunderbolt adapter 3 USB- C Thunderbolt first generation Thunderbolt 2,135.99,0,12585395.00,STA,Startech
6203,STA0035,USB-C Startech VGA Adapter Black,Adapter with reversible USB connection VGA-C (compatible with Thunderbolt 3) Mac and PC,53.99,1,12585395.00,STA,Startech
6204,STA0036,Startech USB Adapter VGA-C Blanco,Adapter with reversible USB connection VGA-C (compatible with Thunderbolt 3) Mac and PC,53.99,1,12585395.00,STA,Startech
6205,STA0031-A,Open - Startech USB-C HDMI Adapter Black,Adapter with USB-C reversible HDMI connection supports Mac and PC conThunderbolt 3,39.99,0,1298.00,STA,Startech
6206,STA0038,Startech USB adapter to HDMI-C White,Adapter with reversible USB-C connection HDMI (compatible with Thunderbolt 3) Mac and PC,39.99,1,12585395.00,STA,Startech
6207,STA0042,Startech USB Adapter DVI-C White,Adapter with USB-C reversible Digital DVI connection (compatible with Thunderbolt 3) Mac and PC,49.99,1,12585395.00,STA,Startech
6208,STA0039,Hub Startech USB to VGA DVI-C Mini DisplayPort HDMI and 4K Aluminum,Hub Thunderbolt connection 3 / USB-C VGA DVI to HDMI and Mini DisplayPort and integrated magnetic cable manager for Mac and PC,128.99,1,12585395.00,STA,Startech
6212,STA0040,Startech USB Hub Charger-C to HDMI 4K 2 USB 3.0 ports and Ethernet Gigabite,Hub Thunderbolt connection 3 / USB to HDMI 4K-C Gigabit Ethernet port and two USB 3.0 ports for Mac and PC,146.99,1,12585395.00,STA,Startech
6213,STA0041,Startech USB Hub-C or VGA to HDMI 4K USB 3.0 and Gigabit Ethernet,Hub with USB-C connection VGA port or HDMI 4K Gigabit Ethernet port and USB 3.0 for Mac and PC,123.99,1,12585395.00,STA,Startech
6226,STA0048,Startech USB-C to USB-C Cable 1m Black (compatible with Thunderbolt 3-port),USB cable connection USB-C-C and reversible design for Mac and PC,14.99,0,1325.00,STA,Startech
6227,STA0060,Startech USB-C Gigabit Ethernet Adapter White,USB-C adapter Gigabit Ethernet high-performance Mac and PC,52.99,1,12585395.00,STA,Startech
6228,STA0050,Startech USB-C Gigabit Ethernet Adapter Silver,C adapter with USB-Gigabit Ethernet connection with compact aluminum design for Mac and PC,63.59,1,12585395.00,STA,Startech
6229,STA0047,Startech USB Hub-C and 3-C USB USB-A Black,Hub with USB-C connection 3 USB-A ports and 1 USB-C port (compatible with Thunderbolt 3) for Mac and PC,52.99,1,12585395.00,STA,Startech
6230,STA0054,Startech USB Hub 3-C USB 3.0 and Gigabit Ethernet Power Adapter,Hub with USB-C connection 3 USB 3.0 ports and an additional port Gigabit Ethernet with power adapter for Mac and PC,93.99,1,12585395.00,STA,Startech
6231,STA0051,Startech USB-C 4K HDMI 60Hz Black,USB-C adapter with HDMI connection (compatible with Thunderbolt 3) for Mac and PC,47.99,1,12585395.00,STA,Startech
6233,STA0049,Startech USB-C Adapter USB 3.1 Gigabit Ethernet + Extra Black,USB-C adapter cable (compatible with Thunderbolt 3) and two connections: Ethernet and USB 3.1 for new MacBook,70.99,0,12585395.00,STA,Startech
6234,STA0061,Startech USB-C Gigabit Ethernet Adapter 2 + USB 3.0 Extra Black,USB-C adapter cable (compatible with Thunderbolt 3) Two Gigabit Ethernet ports and 1 USB 3.0 port for new MacBook,109.99,0,12585395.00,STA,Startech
6236,STA0053,Startech Reader / Writer SD Card 4.0 UHS II 2 slots for USB-C,SD reader and writer SDHC or SDXC cards and USB 3.0 and USB -C connection for Mac and PC,68.99,0,12585395.00,STA,Startech
6237,STA0062,Startech Mini DisplayPort to DisplayPort Cable 18m 4k Black,Cable adapter Mini Displayport to Displayport compatible with 4K content for Mac and PC,11.99,0,1325.00,STA,Startech
6238,STA0063,StarTech Cable FireWire 800 9-6 pins 18m Black,FireWire Cable Firewire 800 connection with 9-pin to 6-pin Firewire for Mac and PC,14.99,0,1325.00,STA,Startech
6246,STA0043,Startech charging cable Thunderbolt 3 05m Black (compatible USB-C),Cable length 05 m with connection Thunderbolt Thunderbolt 3 to 3 for Mac and PC,33.99,1,12585395.00,STA,Startech
6247,STA0044,Startech charging cable 1m Thunderbolt 3 20Gb / s (compatible USB-C) Black,Cable length 3 to 1 meter Thunderbolt Thunderbolt connection 3 for Mac and PC,39.99,1,1325.00,STA,Startech
6248,STA0045,Startech charging cable 2m Thunderbolt 3 20Gb / s (compatible USB-C),Cable length 2 meters connection Thunderbolt Thunderbolt 3 to 3 for Mac and PC,49.99,1,1325.00,STA,Startech
6254,STA0046,Startech USB-C Mini Adapter USB-A Black,Adapter with USB-C connection to USB-A compatible with Thunderbolt 3 for Mac and PC,20.99,1,12585395.00,STA,Startech
6255,STA0052,Startech USB-C 4K HDMI 60Hz White,C USB-HDMI adapter compatible with Thunderbolt 3 Connection for Mac and PC,47.99,1,12585395.00,STA,Startech
6256,STA0058,Startech USB-C to DVI Cable 1m Black,With reversible USB-adapter C Digital DVI connection for Mac and PC,53.99,0,12585395.00,STA,Startech
6258,STA0059,Startech USB-C Cable to VGA 1m Black,1m adapter cable with USB-C reversible VGA connection for Mac and PC,62.99,0,12585395.00,STA,Startech
6264,STA0055,Startech USB-C Adapter USB-A Black,Cable adapter with USB-C to USB 3.0 connection compatible with Thunderbolt 3 for Mac and PC,22.99,1,12585395.00,STA,Startech
6266,STA0056,Startech USB-C Cable DisplayPort 18m 60Hz 4K Black,18m adapter cable with USB-C connection DisplayPort 4K resolution for Mac and PC,53.99,1,12585395.00,STA,Startech
6267,STA0057,Startech USB-C Cable to HDMI 4K 30Hz 2m Black,2 m Cable adapter with USB-C connection to HDMI 4K 30Hz and compact design for Mac and PC,58.99,1,12585395.00,STA,Startech
6402,STA0039-A,Open - Startech Charging Cable Black 2m Thunderbolt 3,Cable length 2 meters connection Thunderbolt Thunderbolt 3 to 3 for Mac and PC,49.99,0,1298.00,STA,Startech
6548,STA0032-A,Open - Startech Thunderbolt Adapter 3 / USB to HDMI-C White,Thunderbolt adapter plug 3 / USB-C HDMI reversibly with light weight design and easy portability,39.99,0,1298.00,STA,Startech
6591,STA0043-A,Open - Startech Thunderbolt Adapter 3 / USB-C to USB 3.1 Gigabit Ethernet + Extra Black,Thunderbolt cable adapter 3 / USB-C and two connections: Ethernet and USB 3.1 for new MacBook,70.99,0,1298.00,STA,Startech
6596,STA0047-A,Open - Startech Reader / Writer SD Card 4.0 UHS II 2 slots for USB-C,SD reader and writer SDHC or SDXC cards and USB 3.0 and USB -C connection for Mac and PC,68.99,0,1298.00,STA,Startech
6883,STA0044-A,Open - USB-C Startech Gigabit Ethernet Adapter Silver,USB-C Gigabit Ethernet connection with compact aluminum design for Mac and PC,63.59,0,1298.00,STA,Startech
7149,STA0064,StarTech Thunderbolt Docking Station 3 With Dual Outputs 4K video,Hub Thunderbolt 3 to multiport USB USB-C 3.1Ethernet audio output and audio input for Mac and PC,422.28,1,12585395.00,STA,Startech
8027,STA0041-A,Open - Startech USB Hub USB-C-C and 3 USB-A Black,Hub with USB-C connection 3 USB-A ports and 1 USB-C port (compatible with Thunderbolt 3) for Mac and PC,52.99,0,1298.00,STA,Startech
8029,STA0020-A,Open - Startech Adapter Lightning to Micro USB-B Female White,Lightning to Micro USB Adapter for iPhone-B generation iPad and iPod Touch 6A.,16.99,0,1298.00,STA,Startech
9023,STA0037,Startech USB-C HDMI Adapter Black,Adapter with USB-C reversible HDMI connection supports Mac and PC conThunderbolt 3,39.99,0,12585395.00,STA,Startech
9855,STA0033-A,Open - Hub Startech USB to VGA DVI-C Mini DisplayPort HDMI and 4K Aluminum,Hub Thunderbolt connection refitted with 3 / USB-C VGA DVI to HDMI and Mini DisplayPort and integrated magnetic cable manager for Mac and PC,128.99,0,12585395.00,STA,Startech
10232,STA0035-A,Open - Startech USB Hub-C or VGA to HDMI 4K USB 3.0 and Gigabit Ethernet,Hub with USB-C connection VGA port or HDMI 4K Gigabit Ethernet port and USB 3.0 for Mac and PC,123.99,0,12585395.00,STA,Startech

In [27]:
# OTR (no changes made to "long", since we are not sure of the names. Hence retained without any changes)
product_brand_df.loc[product_brand_df["brand_name_short"]=="OTR",:]#.shape[0]

,sku,name,desc,price,in_stock,type,brand_name_short,brand name
74,OTR0045,External Slim Case for SuperDrive MacBook / MacBook Pro,External SuperDrive case for MacBook and MacBook Pro.,35.00,1,12995397.00,OTR,Startech
268,OTR0062,StarTech USB adapter mini Bluetooth 2.1,Mini Bluetooth USB for Mac and PC wireless network.,24.99,0,1334.00,OTR,Startech
273,OTR0039,Startech Splitter Adapter 2 headphones,headphone jack adapter 2 Mini-3-pin mini-jack to 4 pin.,9.20,1,1230.00,OTR,Startech
699,OTR0103,Grenade Grip Gopole EmpuÌ ± Adura GoPro camera,EmpuÌ ± Adura for GoPro Hero.,22.99,0,11905404.00,OTR,Startech
700,OTR0104,Xsories Big U-Shot GoPro Camera Extension 95cm Black,95cm extension rod GoPro Hero cameras.,49.99,0,11905404.00,OTR,Startech
701,OTR0107,Xsories 50cm extension U-Shot camera GoPro Silver,Extension Arm for GoPro Hero.,49.99,0,11905404.00,OTR,Startech
938,OTR0075,Startech Ethernet Cable Cat6 10m Black,Ethernet cable 10 meters Unit Class 6 Mac and PC.,11.99,1,1325.00,OTR,Startech
939,OTR0092,StarTech HDMI Extension Cable 2m Black,StarTech HDMI Extension Cable 2m Black.,11.99,0,1325.00,OTR,Startech
942,OTR0031,Startech Cable DVI-I Male to DVI-I (29-pin) 18m,Cable DVI-I Male to DVI-I 18m.,14.98,0,1325.00,OTR,Startech
1432,OTR0120,selfie extendable arm with black Bluetooth button,extensible arm Bluetooth button for selfies.,24.99,0,1216.00,OTR,Startech
1473,OTR0119,Pinpo extensible arm selfie + self-timer,Extensible arm for selfies and self-timer for iPhone.,14.99,0,11905404.00,OTR,Startech
2107,OTR0124,Deeper- Smart Fishfinder Sonar fish,Finder portable wireless fish for iPhone iPad and iPod Touch.,259.99,0,11905404.00,OTR,Startech
3309,OTR0039-A,Open - External Slim Case for SuperDrive MacBook / MacBook Pro,Reconditioned external box SuperDrive for MacBook and MacBook Pro,35.00,0,12995397.00,OTR,Startech
4604,OTR0130,"Brenthaven Fusion case for MacBook Pro Retina 13 ""Black / Green",briefcase with 10 pockets and zippers compartments MacBook Pro Retina 13 / Air 11 inches / 12 inches MacBook / IPAD Pro 129 inches,99.99,0,1392.00,OTR,Startech
5833,OTR0025-A,Open - Startech Cable DVI-I Male to DVI-I (29-pin) 18m,Cable DVI-I Male to DVI-I 18m.,14.98,0,1298.00,OTR,Startech

In [ ]:
product_brand_df.loc[product_brand_df["type"] == "12995397", :]#.shape[0]

In [ ]:
product_brand_df.loc[product_brand_df["sku"] == "OTR0045", :]

In [ ]:
product_brand_df.loc[product_brand_df["sku"] == "STA0045", :]

* No changes made to "long" corresponding to "brand_name_short" of "OTR", since no strong evidence to support any changes, if made. Hence retained without any changes

## Excluding unwanted orders
Only completed orders considered & maintaining same order_ids in both "orders" & "orderline" dataframes

In [ ]:
orders_df["state"].value_counts()

state
Shopping Basket    117809
Completed           46605
Place Order         40883
Pending             14374
Cancelled            7233
Name: count, dtype: int64

In [ ]:
orders_df["order_id"].nunique()

226904

In [ ]:
orderlines_df["order_id"].nunique()

204855

In [ ]:
# Selecting opnly completed orders
orders_df=orders_df.loc[orders_df["state"]== "Completed"]

In [ ]:
orders_df["order_id"].nunique()

46605

In [ ]:
orderlines_df["order_id"].nunique()

204855

* After selecting completed orders, there's a  difference in unique id numbers in both dataframes.
*  Need to ensure that every order_id in orders also exists in orderlines and vice versa for completed orders

In [ ]:
# merging with ordelines
order_orderline = (orders_df
                   .merge(orderlines_df, on="order_id")
    )

order_orderline.head()

,order_id,created_date,total_paid,state,id,product_quantity,sku,orderlines_date,unit_price
0,241423,2017-11-06 13:10:02,136.15,Completed,1398738,1,LAC0212,2017-11-06 12:47:20,129.16
1,242832,2017-12-31 17:40:03,15.76,Completed,1529178,1,PAR0074,2017-12-31 17:26:40,10.77
2,243330,2017-02-16 10:59:38,84.98,Completed,1181923,1,OWC0074,2017-02-15 17:07:44,77.99
3,245275,2017-06-28 11:35:37,149.00,Completed,1276706,1,TAD0007,2017-06-28 11:12:30,149.00
4,245595,2017-01-21 12:52:47,112.97,Completed,1154394,2,PAC1561,2017-01-21 12:49:00,52.99

In [ ]:
order_orderline["order_id"].nunique()

46560

In [ ]:
# order_ids that are in both dataframes
order_ids = order_orderline["order_id"].unique()

In [ ]:
# keeping the common order_ids in orders
orders_df = orders_df.loc[orders_df["order_id"].isin(order_ids), :]

# keeping the common order_ids in orderlines
orderlines_df = orderlines_df.loc[orderlines_df["order_id"].isin(order_ids), :]

In [ ]:
# checking if both dataframes have same unique order_ids
orders_df["order_id"].nunique(), orderlines_df["order_id"].nunique()

(46560, 46560)

## Excluding orders with unknown products

Updating the "orderlines" dataframe to include only known products & removing the unknown products from "orderlines" & "orders"

In [ ]:
# Merging orderlines & product tables using left join to retain all the orders in orderline

orderline_product= orderlines_df.merge(products_df, on= "sku", how= "left")[["order_id","sku","name"]]
orderline_product.sample(10)

,order_id,sku,name
230537,486208,APP1214,Apple Magic Mouse 2
281920,519604,LIF0127,LifeProof Fre X Case iPhone Waterproof Black
64883,355513,JBL0096,GO JBL Bluetooth Portable Speaker Black
203249,463626,SAT0057,Satechi USB Hub Adapter Pro-C PD Space Gray
147659,427061,WAC0221,Education - Wacom Intuos Pro M South Graphics Tablet
235183,489093,SAT0053,Satechi Multiport USB Hub HDMI 4K-C Plata
91354,378072,NTE0045,NewerTech NuGuard KX iPhone Case SE / 5s / 5 Black
77553,366360,APP1221,Apple Pencil
18581,315933,KEN0212,Kensington Power Bank External Battery 5200mAh Silver
69794,359605,TOS0022,"Toshiba Canvio Basic 25 ""3TB USB 3.0 Black"

In [ ]:
orderline_product["name"].isna().value_counts()

name
False    292441
True       1542
Name: count, dtype: int64

* There are 393 unknown products.
* So instead of deleting these rows,removing the entirety of any order that contains an unknown product to keep a consistent & coherent dataset seems to be a better approach.

In [ ]:
orders_to_delete = orderline_product.loc[orderline_product.name.isna(), "order_id"].unique()
orders_to_delete

array([299638, 299706, 299712, ..., 515700, 521165, 521667])

* Updating orders & orderline tables by removing the order ids in the corrupted list (orders_to_delete)

In [ ]:
orders_df= orders_df.loc[~ orders_df["order_id"].isin(orders_to_delete),:]

In [ ]:
orderlines_df= orderlines_df.loc[~ orderlines_df["order_id"].isin(orders_to_delete),:]

In [ ]:
# checking if both dataframes have same ids
orders_df["order_id"].nunique(), orderlines_df["order_id"].nunique()

(226904, 204855)

In [ ]:
orderline_product["sku"].nunique()

7951

## Exploring the price details/ Revenue

### Excluding the ouitliers in 2 Approaches:
1. Median Deviation (MAD) method- for removing order_ids where unit_price differ from median ( 50%-200% of median_price)
2. IQR method- for removing order_ids where difference in total paid & total unit price differences are high

#### 1. Median deviation method

In [ ]:
orders_df_m = orders_df.copy()
orderlines_df_m = orderlines_df.copy()

In [ ]:
orderlines_df_m["median_price"] = orderlines_df_m.groupby("sku")["unit_price"].transform("median")

In [ ]:
orderlines_df_m["price_ratio"] = orderlines_df_m["unit_price"] / orderlines_df_m["median_price"]

In [ ]:
orderlines_df_m

,id,order_id,product_quantity,sku,orderlines_date,unit_price,median_price,price_ratio
7,1119116,299545,1,OWC0100,2017-01-01 01:46:16,47.49,49.99,0.95
8,1119119,299546,1,IOT0014,2017-01-01 01:50:34,18.99,16.99,1.12
9,1119120,295347,1,APP0700,2017-01-01 01:54:11,72.19,67.99,1.06
11,1119126,299549,1,PAC0929,2017-01-01 02:07:42,2565.99,2721.99,0.94
18,1119134,299556,1,CRU0039-A,2017-01-01 02:20:14,60.90,60.90,1.00
...,...,...,...,...,...,...,...,...
293599,1649474,525664,1,TUC0207,2018-03-14 11:45:05,16.52,19.99,0.83
293616,1649512,527070,2,APP0698,2018-03-14 11:49:01,9.99,9.99,1.00
293621,1649522,527074,2,APP0698,2018-03-14 11:49:36,9.99,9.99,1.00
293644,1649565,527096,3,APP0698,2018-03-14 11:54:35,9.99,9.99,1.00
293661,1649593,527112,1,APP0698,2018-03-14 11:58:13,9.99,9.99,1.00

* Keeping the range between 50% -200% of median :
  1.  Since median represents the typical price & is robust to extreme values, so it gives a good estimate of the “normal” price for that product.

  2. Allow normal variation in Prices, which can vary due to discounts,promotions, packaging differences etc. Allowing ±50% -100% variation keeps legitimate prices.

  3. Symmetric tolerance around the typical price 0.5 × median → allows up to 50% cheaper 2 × median → allows up to 100% more expensive

In [ ]:
# identifying the outlier order_ids whose price either 2 times higher or 0.5 times lesser than unit price
outlier_order_id =orderlines_df_m.loc[(orderlines_df_m["price_ratio"] > 2) | (orderlines_df_m["price_ratio"] < 0.5),"order_id"].unique()
outlier_order_id

array([300436, 300475, 300540, 301652, 302679, 303560, 303697, 304299,
       304541, 306081, 307634, 308157, 308669, 308786, 309031, 309372,
       310228, 310294, 310190, 310614, 311548, 312454, 313110, 313353,
       313462, 307835, 314002, 314240, 315859, 317037, 317046, 317118,
       315217, 317454, 317432, 318410, 320232, 320326, 321590, 325128,
       325772, 325751, 325978, 326915, 345553, 345626, 345663, 345792,
       346030, 347681, 347233, 349856, 350623, 353736, 354044, 354697,
       354702, 354748, 354759, 354766, 354802, 354861, 354873, 354991,
       355097, 355185, 354980, 356005, 357388, 358025, 360910, 361327,
       359689, 361360, 364367, 366940, 367272, 369169, 370637, 375126,
       376219, 376457, 376616, 379925, 382405, 386460, 388586, 402694,
       421208, 422168, 423135, 426069, 428048, 433753, 433893, 430250,
       436345, 436485, 437760, 437953, 438260, 438672, 439799, 440553,
       440559, 441021, 443713, 444112, 445223, 445719, 446009, 446792,
       447356, 447835, 447946, 448073, 448203, 451775, 452280, 454986,
       457373, 457539, 461476, 463960, 465523, 467245, 469083, 470137,
       470715, 472217, 474004, 472406, 475451, 471171, 476084, 476888,
       477558, 478886, 483229, 484245, 484464, 485614, 486771, 486801,
       487477, 487526, 487706, 488160, 489780, 489818, 492098, 493484,
       496849, 497563, 500877, 507773, 511665, 512043, 512051, 512145,
       512150, 512215, 512413, 512444, 512451, 512456, 512498, 512517,
       512522, 512530, 512531, 512536, 512556, 512568, 512618, 256799,
       512656, 512680, 512641, 512697, 512739, 512742, 508741, 512773,
       512791, 512807, 511204, 512834, 512862, 512867, 512871, 450333,
       512941, 512963, 512969, 513009, 513033, 513049, 513190, 513298,
       509673, 513447, 513686, 513728, 514134, 514166, 514220, 516969,
       519392, 522146])

In [ ]:
# Updating orders & orderline dataframes by removing the outlier order ids in the list (outlier_order_id )

In [ ]:
orders_df_m= orders_df_m.loc[~ orders_df_m["order_id"].isin(outlier_order_id),:]

In [ ]:
orderlines_df_m= orderlines_df_m.loc[~ orderlines_df_m["order_id"].isin(outlier_order_id),:]

In [ ]:
# checking if both dataframes have same ids
orders_df_m["order_id"].nunique(), orderlines_df_m["order_id"].nunique()

(45962, 45962)

In [ ]:
orderlines_df_m.describe().round(2)

,id,order_id,product_quantity,orderlines_date,unit_price,median_price,price_ratio
count,60918.00,60918.00,60918.00,60918,60918.00,60918.00,60918.00
mean,1387181.16,415039.41,1.12,2017-09-13 00:26:01.006205184,238.46,238.21,1.00
min,1119116.00,241423.00,1.00,2017-01-01 01:46:16,0.01,0.01,0.50
25%,1268715.25,363926.75,1.00,2017-06-15 13:22:40.750000128,29.74,29.99,0.98
50%,1391490.50,418056.00,1.00,2017-10-28 23:53:58.500000,69.99,69.99,1.00
75%,1514727.50,470494.50,1.00,2017-12-25 19:49:29.500000,185.99,185.99,1.00
max,1649593.00,527112.00,72.00,2018-03-14 11:58:13,8287.80,8287.80,2.00
std,150388.83,65365.42,0.76,NaN,495.90,495.42,0.09

In [ ]:
orderlines_df_m.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60918 entries, 7 to 293661
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                60918 non-null  int64
 1   order_id          60918 non-null  int64
 2   product_quantity  60918 non-null  int64
 3   sku               60918 non-null  object
 4   orderlines_date   60918 non-null  datetime64[ns]
 5   unit_price        60918 non-null  float64
 6   median_price      60918 non-null  float64
 7   price_ratio       60918 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(3), object(1)
memory usage: 4.2+ MB

#### 2. IQR method

In [ ]:
# creating new column with unit_price total
orderlines_df_m["unit_price_total"] = (orderlines_df_m["unit_price"])* (orderlines_df_m["product_quantity"])

# filtering to view only required columns for price comparison
orderlines_pc= orderlines_df_m[["order_id", "product_quantity","sku", "unit_price","unit_price_total"]]
orderlines_pc.sample(10)

/tmp/ipykernel_6346/443553606.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orderlines_df_m["unit_price_total"] = (orderlines_df_m["unit_price"])* (orderlines_df_m["product_quantity"])

        order_id  product_quantity        sku  unit_price  unit_price_total
211213    470819                 1    APP2477      785.08            785.08
259187    503818                 1    SAT0062       49.99             49.99
106162    390911                 1    APP2125      832.81            832.81
272756    512662                 1    MOP0105        9.99              9.99
133718    414974                 1  BLL0004-A       12.72             12.72
56667     348616                 4    CRU0022       44.99            179.96
265962    507874                 1    BLM0021      139.99            139.99
2154      301563                 1    APP1135       55.00             55.00
94063     380506                 1    AP20120       32.99             32.99
61069     352187                 1    SEA0102      103.99            103.99

In [ ]:
# Groupingby order_id & aggregating by unit_price_total to find the total for each order
orderlines_order_ids_m = orderlines_pc.groupby("order_id",as_index=False)["unit_price_total"].sum()
orderlines_order_ids_m

       order_id  unit_price_total
0        241423            129.16
1        242832             10.77
2        243330             77.99
3        245275            149.00
4        245595            105.98
...         ...               ...
45957    527042             13.99
45958    527070             19.98
45959    527074             19.98
45960    527096             29.97
45961    527112              9.99

[45962 rows x 2 columns]

In [ ]:
diff_df_m= orders_df_m.merge(orderlines_order_ids_m,on ="order_id")
diff_df_m["difference"]= (diff_df_m["total_paid"]) - (diff_df_m["unit_price_total"])
diff_df_m

,order_id,created_date,total_paid,state,unit_price_total,difference
0,241423,2017-11-06 13:10:02,136.15,Completed,129.16,6.99
1,242832,2017-12-31 17:40:03,15.76,Completed,10.77,4.99
2,243330,2017-02-16 10:59:38,84.98,Completed,77.99,6.99
3,245275,2017-06-28 11:35:37,149.00,Completed,149.00,0.00
4,245595,2017-01-21 12:52:47,112.97,Completed,105.98,6.99
...,...,...,...,...,...,...
45957,527042,2018-03-14 11:47:50,18.98,Completed,13.99,4.99
45958,527070,2018-03-14 11:50:48,24.97,Completed,19.98,4.99
45959,527074,2018-03-14 11:51:42,24.97,Completed,19.98,4.99
45960,527096,2018-03-14 11:58:40,34.96,Completed,29.97,4.99
45961,527112,2018-03-14 12:03:52,14.98,Completed,9.99,4.99

In [ ]:
diff_df_m.loc[diff_df_m["difference"] < 0,:]. sort_values("difference",ascending= True).head(20)

,order_id,created_date,total_paid,state,unit_price_total,difference
26034,432303,2017-11-22 21:43:02,261.86,Completed,426.86,-165.00
82,289685,2017-01-09 23:15:07,15.95,Completed,135.97,-120.02
5495,319901,2017-02-04 16:09:34,60.43,Completed,142.44,-82.01
341,300474,2017-01-02 12:24:54,119.00,Completed,164.90,-45.90
4041,314570,2017-01-25 09:01:35,122.99,Completed,164.90,-41.91
7241,327363,2017-02-21 22:42:17,122.99,Completed,164.90,-41.91
2473,308825,2017-01-13 14:27:46,123.99,Completed,164.90,-40.91
6027,322147,2017-02-10 11:56:59,125.99,Completed,164.90,-38.91
3398,312311,2017-01-20 00:59:54,125.99,Completed,164.90,-38.91
1931,306927,2017-01-10 23:18:53,130.99,Completed,164.90,-33.91
8789,349375,2017-04-24 21:39:47,4.99,Completed,35.00,-30.01
373,300590,2017-01-02 15:59:32,44.98,Completed,69.98,-25.00
369,300572,2017-01-03 11:51:38,21.99,Completed,46.99,-25.00
575,301313,2017-01-03 09:11:20,55.99,Completed,80.99,-25.00
2754,310031,2017-01-15 23:06:25,44.99,Completed,69.99,-25.00
636,301495,2017-01-03 12:22:02,0.00,Completed,24.99,-24.99
96,296010,2017-01-09 23:47:00,0.00,Completed,24.99,-24.99
1333,304608,2017-01-08 02:32:43,65.97,Completed,86.98,-21.01
1781,306362,2017-01-10 11:46:21,33.98,Completed,54.99,-21.01
104,296847,2017-01-15 18:31:58,30.97,Completed,51.98,-21.01

In [ ]:
diff_df_m.describe().round(2)

,order_id,created_date,total_paid,unit_price_total,difference
count,45962.00,45962,45962.00,45962.00,45962.00
mean,415443.43,2017-09-13 07:19:39.866781440,337.46,333.28,4.18
min,241423.00,2017-01-01 01:51:47,0.00,2.49,-165.00
25%,363499.25,2017-06-13 13:02:43.500000,50.98,46.99,0.00
50%,418468.50,2017-10-30 01:36:21.500000,112.99,108.99,4.99
75%,471271.75,2017-12-26 12:40:44.249999872,330.99,325.99,6.99
max,527112.00,2018-03-14 12:03:52,13387.78,13387.77,3984.99
std,65718.93,NaN,616.43,616.71,24.57

In [ ]:
# calculating the quartiles
Q1 = diff_df_m["difference"].quantile(0.25)
Q3 = diff_df_m["difference"].quantile(0.75)

Q1, Q3

(np.float64(0.0), np.float64(6.989999999999981))

In [ ]:
# calculating the interquartile range
IQR = Q3-Q1
# lower boundary
L= Q1 - 1.5*IQR
# upper boundary
U= Q3 + 1.5*IQR
print(f" Lower boundary: {L}\n Upper boundary: {U}")

 Lower boundary: -10.484999999999971
 Upper boundary: 17.47499999999995

In [ ]:
# filter the DataFrame to include only "non-outliers"
diff_no_outliers_df = diff_df_m.loc[
    (diff_df_m["difference"] >= (L))
    &
    (diff_df_m["difference"] <= (U))
    ,
    :]

In [ ]:
normal_diff_list = diff_no_outliers_df["order_id"]

In [ ]:
orders_df_m = orders_df_m.loc[orders_df_m["order_id"].isin(normal_diff_list), :]
orderlines_df_m = orderlines_df_m.loc[orderlines_df_m["order_id"].isin(normal_diff_list), :]

In [ ]:
# checking if both dataframes have same ids
orders_df_m["order_id"].nunique(), orderlines_df_m["order_id"].nunique()

(45238, 45238)

In [ ]:
orderlines_df_m.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59808 entries, 7 to 293661
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                59808 non-null  int64
 1   order_id          59808 non-null  int64
 2   product_quantity  59808 non-null  int64
 3   sku               59808 non-null  object
 4   orderlines_date   59808 non-null  datetime64[ns]
 5   unit_price        59808 non-null  float64
 6   median_price      59808 non-null  float64
 7   price_ratio       59808 non-null  float64
 8   unit_price_total  59808 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(1)
memory usage: 4.6+ MB

## Checking the quality of data selected for analysis

In [ ]:
orders_df_m.describe().round(2)

       order_id                   created_date  total_paid
count  45238.00                          45238    45238.00
mean  415300.41  2017-09-12 20:23:56.105840128      338.48
min   241423.00            2017-01-01 01:51:47        2.82
25%   363096.75            2017-06-12 11:08:41       49.99
50%   418255.00            2017-10-29 12:07:04      112.00
75%   471179.00  2017-12-26 11:34:02.750000128      330.98
max   527112.00            2018-03-14 12:03:52    13387.78
std    65749.02                            NaN      619.71

In [ ]:
orders_df= orders_df_m

In [ ]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45238 entries, 1 to 226614
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      45238 non-null  int64
 1   created_date  45238 non-null  datetime64[ns]
 2   total_paid    45238 non-null  float64
 3   state         45238 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 1.7+ MB

In [ ]:
orderlines_df_m.describe().round(2)

,id,order_id,product_quantity,orderlines_date,unit_price,median_price,price_ratio,unit_price_total
count,59808.00,59808.00,59808.00,59808,59808.00,59808.00,59808.00,59808.00
mean,1386609.06,414869.50,1.12,2017-09-12 10:23:12.743546112,240.08,239.31,1.00,253.19
min,1119116.00,241423.00,1.00,2017-01-01 01:46:16,0.01,0.01,0.51,0.01
25%,1266616.75,363249.75,1.00,2017-06-12 17:06:13,29.90,29.99,0.99,29.99
50%,1390673.50,417835.50,1.00,2017-10-27 16:58:06,70.39,69.99,1.00,77.28
75%,1514531.00,470406.00,1.00,2017-12-25 16:56:10.750000128,186.58,185.99,1.01,208.99
max,1649593.00,527112.00,72.00,2018-03-14 11:58:13,8287.80,8287.80,2.00,13387.77
std,150615.24,65405.01,0.77,NaN,499.38,498.56,0.09,522.13

In [ ]:
orderlines_df= orderlines_df_m[["id","order_id","product_quantity","sku","orderlines_date","unit_price","unit_price_total"]]

In [ ]:
orderlines_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59808 entries, 7 to 293661
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                59808 non-null  int64
 1   order_id          59808 non-null  int64
 2   product_quantity  59808 non-null  int64
 3   sku               59808 non-null  object
 4   orderlines_date   59808 non-null  datetime64[ns]
 5   unit_price        59808 non-null  float64
 6   unit_price_total  59808 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(1)
memory usage: 3.7+ MB

In [ ]:
products_df.describe().round(2)

         price  in_stock                type
count 10534.00  10534.00            10484.00
mean    641.16      0.19  146302850159717.69
std    1337.86      0.40  903238784037626.12
min       2.99      0.00             1216.00
25%      42.05      0.00             1433.00
50%     103.22      0.00         11905404.00
75%     599.00      0.00         12645406.00
max   15339.00      1.00 5740000000000000.00

In [ ]:
products_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10534 entries, 0 to 10533
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sku        10534 non-null  object
 1   name       10534 non-null  object
 2   desc       10534 non-null  object
 3   price      10534 non-null  float64
 4   in_stock   10534 non-null  int64
 5   type       10484 non-null  float64
 6   short_sku  10534 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 576.2+ KB

# Importing Quality controlled Data

In [ ]:
# renaming the dataframes
orders_qc= orders_df
orderlines_qc = orderlines_df
products_qc = products_df

In [ ]:
from google.colab import files

In [ ]:
orders_qc.to_csv("orders_qc.csv", index=False)
files.download("orders_qc.csv")

orderlines_qc.to_csv("orderlines_qc.csv", index=False)
files.download("orderlines_qc.csv")

products_qc.to_csv("products_qc.csv", index=False)
files.download("products_qc.csv")